print(1 > 2)  # retorna false
print(1 < 2)  # retorna true
print(1 <= 2)  # retorna true
print(1 >= 2)  # retorna false
print(2 >= 2)  # retorna true
print(2 <= 2)  # retorna true
print(2 == 2)  # retorna true
print(2 == 3)  # retorna false
print(2 == "2")  # retorna false
print(2 != "2")  # retorna true
print(2 != 2)  # retorna false
